apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: index-observer
resources:
- ../../base
- monitor.yaml
replicas:
- name: index-observer
  count: 1
patchesStrategicMerge:
- patch.yaml
images:
- name: index-observer
  newName: 407967248065.dkr.ecr.us-east-2.amazonaws.com/index-observer/index-observer # {"$imagepolicy": "index-observer:index-observer:name"}
  newTag: 20230317100316-09a972f79dd74680d9aa6d2b8b127021acb9bb9f # {"$imagepolicy": "index-observer:index-observer:tag"}
