apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-observer
  namespace: index-observer
spec:
  template:
    spec:
      containers:
        - name: index-observer
          image: index-observer
          resources:
            requests:
              cpu: "3.5"
              memory: 10Gi
