apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-observer
  namespace: index-observer
spec:
  template:
    spec:
      containers:
        - name: index-observer
          image: index-observer
          args:
            - --port=8080
            - --indexer=https://cid.contact
            - --sources=https://dev.cid.contact,https://cid.contact,https://cid.contact,https://cid.contact,https://cid.contact
            - --targets=https://ago.dev.cid.contact,https://inga.prod.cid.contact,https://arya.prod.cid.contact,https://bala.prod.cid.contact,https://cera.prod.cid.contact
          resources:
            limits:
              cpu: "3.5"
              memory: 10Gi
            requests:
              cpu: "3.5"
              memory: 10Gi
