name: Container

on: [ push, pull_request ]

jobs:
  publisher:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Container Image
        env:
          DOCKER_BUILDKIT: '1'
        run: docker build -t "index-observer:${GITHUB_SHA}" .
      - name: Check Container Image
        run: docker run "index-observer:${GITHUB_SHA}" help